######################################################################
# Automatically generated by qmake (3.0) ?? 11? 10 21:14:39 2014
######################################################################

TEMPLATE = app
TARGET = UINode
INCLUDEPATH += .

# Input
HEADERS += PingThread.h RosThread.h ../HelperFunctions.h \
    myros_ardrone_gui.h
FORMS += \
    myros_ardrone_gui.ui
SOURCES += main_GUI.cpp PingThread.cpp RosThread.cpp \
    myros_ardrone_gui.cpp
