######################################################################
# Automatically generated by qmake (3.0) ?? 11? 10 21:14:39 2014
######################################################################

TEMPLATE = app
TARGET = UINode
INCLUDEPATH += .

# Input
HEADERS += PingThread.h RosThread.h tum_ardrone_gui.h ../HelperFunctions.h
FORMS += tum_ardrone_gui.ui
SOURCES += main_GUI.cpp PingThread.cpp RosThread.cpp tum_ardrone_gui.cpp
